<div class="cards-grid">
    <h3>CONHEÇA NOSSOS DIFERENCIAIS</h3>
    <ul>
        <li>
            <img src="<?= $block->getViewFileUrl('images/card1.png') ?>"/>
        </li>
        <li>
            <img src="<?= $block->getViewFileUrl('images/card2.png') ?>"/>
        </li>
        <li>
            <img src="<?= $block->getViewFileUrl('images/card3.png') ?>"/>
        </li>
        <li>
            <img src="<?= $block->getViewFileUrl('images/card4.png') ?>"/>
        </li>
        <li>
            <img src="<?= $block->getViewFileUrl('images/card5.png') ?>"/>
        </li>
    </ul>
</div>