<div class="how-it-works">
    <h2>Como Funciona</h2>
    <ul>
        <li>
            <img src="<?= $block->getViewFileUrl('images/navegue-pelo-cardapio.jpg') ?>" alt="Navegue pelo cardápio" />
            <h3>Navegue pelo cardápio</h3>
            <p>Pratos saudáveis e deliciosos que facilitam seu dia e se encaixam na sua rotina.</p>
        </li>
        <li>
            <img src="<?= $block->getViewFileUrl('images/monte-seu-combo.jpg') ?>" alt="Navegue pelo cardápio" />
            <h3>Monte seu Combo</h3>
            <p>Escolha os seus pratos favoritos. Quanto mais você compra, menos paga.</p>
        </li>
        <li>
            <img src="<?= $block->getViewFileUrl('images/agende-a-entrega.jpg') ?>" alt="Navegue pelo cardápio" />
            <h3>Agende<br>a entrega</h3>
            <p>Entregas em 24h. Você escolhe o dia e a hora para receber na porta da sua casa.</p>
        </li>
        <li>
            <img src="<?= $block->getViewFileUrl('images/zero-esforco.jpg') ?>" alt="Navegue pelo cardápio" />
            <h3>Fácil,<br>zero esforço!</h3>
            <p>Você só esquenta. Do freezer para o forno ou micro-ondas. Pronto em poucos minutos.</p>
        </li>
    </ul>
</div>